In [1]:
##Day-8
#numpy means numerical python
import numpy as np

In [7]:
##create 1D numpy array
x = np.array([56,87,98,34])
print(x)
print(type(x))
print(x.dtype)

[56 87 98 34]
<class 'numpy.ndarray'>
int32


In [9]:
##verify the data type in array
x = np.array([56,87,98,3.4])
print(x)
print(type(x))
print(x.dtype)

[56.  87.  98.   3.4]
<class 'numpy.ndarray'>
float64


In [11]:
##verify the data type 
x = np.array(["A",87,98,3.4])
print(x)
print(type(x))
print(x.dtype)

['A' '87' '98' '3.4']
<class 'numpy.ndarray'>
<U32


In [13]:
## create 2D array
a2 = np.array([[20,30],[80,90]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 30]
 [80 90]]
<class 'numpy.ndarray'>
(2, 2)


In [15]:
#Reshaping an array
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [21]:
#Create an array with arange()
c = np.arange(6,19)
print(c)
type(c)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18]


numpy.ndarray

In [25]:
#Use of around()
d = np.array([1.3467, 3.10987, 4.91236])
print(d)
np.around(d,2)

[1.3398 3.8976 7.997 ]


array([1.34, 3.9 , 8.  ])

In [29]:
#use of np.sqrt()
d = np.array([1.3467, 3.10987, 4.91236])
print(d)
print(np.around(np.sqrt(d),2))


[1.3467  3.10987 4.91236]
[1.16 1.76 2.22]


In [35]:
#Create a 2d array
a1 = np.array([[3,4,5,8],[7,2,8,np.NAN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [118]:
# Use of astype() to convert the data type
a1 = np.array([[3,4,5,8],[7,2,8,np.NAN]])
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [114]:
a2 = np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [116]:
a2.sum(axis=1)

array([13, 26, 22])

In [120]:
a2.sum(axis=0)

array([14, 19, 28])

In [124]:
a2.mean(axis=0)

array([4.66666667, 6.33333333, 9.33333333])

In [126]:
a2.mean(axis=1)

array([4.33333333, 8.66666667, 7.33333333])

In [128]:
np.sqrt(a2)

array([[1.73205081, 2.        , 2.44948974],
       [2.64575131, 3.        , 3.16227766],
       [2.        , 2.44948974, 3.46410162]])

In [130]:
##Matrix opeartions
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
a3

array([[3, 4, 5],
       [7, 2, 8],
       [9, 1, 6]])

In [136]:
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [140]:
##MAtrix  multiplication
A = np.array([[1,2], [3,4]])
B = np.array([[5,6],[7,8]])
C = np.matmul(A, B)
print(C)

[[19 22]
 [43 50]]


In [142]:
#Print the Transpose of matrix
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [144]:
##Acessing the array elements
a4 = np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9, 18]])

In [146]:
a4[2][2]

6

In [148]:
a4[2][0]

9

In [152]:
#Slicing 
a4[1:3,0:2]

array([[7, 2],
       [9, 1]])

In [154]:
a4[1:3,0:]

array([[7, 2, 8],
       [9, 1, 6]])

In [156]:
#Acessing max value and its index
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
a3

array([[3, 4, 5],
       [7, 2, 8],
       [9, 1, 6]])

In [158]:
print(np.argmax(a3,axis=1))
print(np.argmax(a3,axis=0))

[2 2 0]
[2 0 1]


In [160]:
#print the max value
print(np.amax(a3, axis = 1))
print(np.amax(a3, axis = 0))

[5 8 9]
[9 4 8]
